# Used for desktop screenshots and when the window name can't be determined
Fallback = 'desktop'

# The root directory where screenshots should be stored
# Screenshots will be named ScreenshotDir/application/timestamp.png or
# ScreenshotDir/application/year/timestamp.png
ScreenshotDir = '/home/kethsar/documents/images/screenshots'

# Will be ignored in favour of any available children
IgnoredParents = ['kitty', 'xfce4-terminal', 'zsh', 'urxvt', 'bash', 'wine-preloader']

# Comment to skip checking WINDOWID if you only use terminals that use a single
# process per window.
# Doesn't help with gnome-terminal, which is uniquely incapable and does not
# set WINDOWID.
CheckWindowID = true

# Callback to be called with the path to the screenshot.
Callback = '/home/kethsar/.config/screenshotter/callback.sh'

# PNG compression level in the range of 0-9
# 0 is fastest, 9 is slowest
# 8 and 9 are slow enough to be annoying for interactive usage
# 0 compresses very poorly and saves little time over 1
Compression = 5

# Overrides. The first one with a matching name and Regex is used.
#
# Name: The application name to match against. Multiple overrides can be
# specified for a name.
#
# Regex: Optional. If present, the full command line is matched against this
# regular expression and the groups can be referenced in the Format.
#
# Yearly: Optional boolean.
# If present and true separate directories will be used
#
# Monthly: Optional boolean.
# If present and true, use separate directories for each
# month. If Yearly is true the directories will be nested (appname/2019/02/),
# but false or absent will result in a flatter structure (appname/2019-02/).
#
# Format: Optional printf style format string.
# The output pattern as a format string. Use %s to
# reference the groups from the regex match, if present. All special
# characters will be escaped, and this cannot be used to specify nested
# directories.
#
# Delegate: Optional executable.
# If present this executable is invoked with several environment variables set,
# see the README for the set of variables.
# A non-zero exit value is treated as a non-match.
# Each line of stdout is treated as a directory on a path rooted at
# ScreenshotDir. If the output is non-empty it will override any value from
# Format.
#

[[Overrides]]
  Name = "chromium-browser"
  Format = "chromium"
  Yearly = true

[[Overrides]]
  Name = "firefox-bin"
  Format = "firefox"
  Yearly = true

[[Overrides]]
  Name = "firefox"
  Yearly = true
 
[[Overrides]]
  Name = "urxvt"
  Yearly = true

[[Overrides]]
  Name = "mpv"
  Yearly = true

[[Overrides]]
  Name = "looking-glass-client"
  Delegate = "/home/kethsar/.config/screenshotter/lg_delegate.sh"

[[Overrides]]
  Name = "wine-preloader"
  Delegate = "/home/kethsar/.config/screenshotter/wine_delegate.sh"

[[Overrides]]
  Name = "wine64-preloader"
  Delegate = "/home/kethsar/.config/screenshotter/wine_delegate.sh"

[[Overrides]]
  Name = "python3-7m"
  Delegate = "/home/kethsar/.config/screenshotter/anki_delegate.sh"
